exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [ commit ]
fail_fast: true

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        language_version: python3.8
        types: [ python ]
        args: [ '--config=setup.cfg' ]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3.8
        types: [ python ]
        args: [ '--config=pyproject.toml' ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        language_version: python3.8
        types: [ python ]
        args: [ '--settings-path=setup.cfg' ]
