version: '3'

volumes:
  local_postgres_data: { }

services:
  app: &app
    depends_on:
      - postgres
      - mailhog
    build:
      context: .
      dockerfile: ./compose/local/application/Dockerfile
    image: pomodoro_system_local
    volumes:
      - "./pomodoro_system:/usr/src/app/pomodoro_system"
    ports:
      - "8000:8000"
    env_file:
      - .envs/local/.application
      - .envs/local/.database
      - .envs/local/.security
      - .envs/local/.mail
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/database/Dockerfile
    image: pomodoro_database_local
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/local/.database
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *app
    image: pomodoro_celeryworker_local
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *app
    image: pomodoro_celerybeat_local
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *app
    image: pomodoro_flower_local
    command: /start-flower
    ports:
      - "5555:5555"