version: '3'

volumes:
  local_postgres_data: { }

services:
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: compose/local/application/Dockerfile
    image: pomodoro_system_local
    volumes:
      - "./pomodoro_system:/usr/src/app"
    ports:
      - "8000:8000"
    env_file:
      - .envs/local/.application
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/database/Dockerfile
    image: pomodoro_database_local
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/local/.database
