#!/bin/bash

set -o errexit
set -o nounset
cd pomodoro_system

celery flower \
    --app=web_app.celery \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
